title: Abhishek Mamdapure # your name (or website title) here
logo: "/images/abhishek_profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Practitioner | Statistical Learning | Natural Language Processing   
  <br><br>
  
  <br><br>
  
  <p>
  <a href="https://www.linkedin.com/in/abhishekmamdapure/">
  <img border="0" alt="LinkedIn" src="/images/linkedin_logo.png" width="35" height="35">
  </a>
  
  <a href="https://github.com/abhishekmamdapure">
  <img border="0" alt="Github" src="/images/github_logo.png" width="35" height="35">
  </a>
  
  <a href="https://medium.com/@mamdapureabhishek">
  <img border="0" alt="Medium" src="/images/medium_logo.png" width="35" height="35">
  </a> 
  
  <a href="mailto:mamdapureabhishek@gmail.com">
  <img border="0" alt="Gmail" src="/images/gmail_logo.png" width="35" height="35">
  </a>
  
  <a href="https://twitter.com/afor_abhishek">
  <img border="0" alt="Twitter" src="/images/twitter_logo.png" width="35" height="35">
  </a>
  </p>
  
 
<html>
<head>
<style>
.button {
  background-color: #48D4F5; /* Green */
  border: 0.5;
  color: black;
  padding: 9px 12px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 13px;
  margin: 4px 2px;
  cursor: pointer;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
}


.button2:hover {
  box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
}
</style>
</head>
<body>



<p>
<a href="/pdf/abhishek_CV.pdf" download="Abhishek_Mamdapure.pdf">
<button class="button button2">Download CV</button>

<a href="/contact.html">
<button class="button button2">Contact Me</button>
</p>
</body>
</html>

  
  
  
  
   
  
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
